routes:
 
collections:
  /:
    permalink: /{slug}/
    template: index

  /speakers/:
    permalink: /speaker/{slug}/
    template: speaker
    filter: tag:speaker+tag:-partner

  /partners/:
    permalink: /partner/{slug}/
    template: partner
    filter: tag:partner+tag:-speaker

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
